# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/muhammad/Desktop/CS2341/22s-pa03-MuhAsh99

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/muhammad/Desktop/CS2341/22s-pa03-MuhAsh99/cmake-build-debug

# Include any dependencies generated for this target.
include CMakeFiles/PA03_sorting_mystery.dir/depend.make
# Include the progress variables for this target.
include CMakeFiles/PA03_sorting_mystery.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/PA03_sorting_mystery.dir/flags.make

CMakeFiles/PA03_sorting_mystery.dir/main.cpp.o: CMakeFiles/PA03_sorting_mystery.dir/flags.make
CMakeFiles/PA03_sorting_mystery.dir/main.cpp.o: ../main.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/Users/muhammad/Desktop/CS2341/22s-pa03-MuhAsh99/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/PA03_sorting_mystery.dir/main.cpp.o"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/PA03_sorting_mystery.dir/main.cpp.o -c /Users/muhammad/Desktop/CS2341/22s-pa03-MuhAsh99/main.cpp

CMakeFiles/PA03_sorting_mystery.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/PA03_sorting_mystery.dir/main.cpp.i"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /Users/muhammad/Desktop/CS2341/22s-pa03-MuhAsh99/main.cpp > CMakeFiles/PA03_sorting_mystery.dir/main.cpp.i

CMakeFiles/PA03_sorting_mystery.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/PA03_sorting_mystery.dir/main.cpp.s"
	/Library/Developer/CommandLineTools/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /Users/muhammad/Desktop/CS2341/22s-pa03-MuhAsh99/main.cpp -o CMakeFiles/PA03_sorting_mystery.dir/main.cpp.s

# Object files for target PA03_sorting_mystery
PA03_sorting_mystery_OBJECTS = \
"CMakeFiles/PA03_sorting_mystery.dir/main.cpp.o"

# External object files for target PA03_sorting_mystery
PA03_sorting_mystery_EXTERNAL_OBJECTS =

PA03_sorting_mystery: CMakeFiles/PA03_sorting_mystery.dir/main.cpp.o
PA03_sorting_mystery: CMakeFiles/PA03_sorting_mystery.dir/build.make
PA03_sorting_mystery: ../lib/libmystery_sorting_mac_intel.a
PA03_sorting_mystery: CMakeFiles/PA03_sorting_mystery.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/Users/muhammad/Desktop/CS2341/22s-pa03-MuhAsh99/cmake-build-debug/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX executable PA03_sorting_mystery"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/PA03_sorting_mystery.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/PA03_sorting_mystery.dir/build: PA03_sorting_mystery
.PHONY : CMakeFiles/PA03_sorting_mystery.dir/build

CMakeFiles/PA03_sorting_mystery.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/PA03_sorting_mystery.dir/cmake_clean.cmake
.PHONY : CMakeFiles/PA03_sorting_mystery.dir/clean

CMakeFiles/PA03_sorting_mystery.dir/depend:
	cd /Users/muhammad/Desktop/CS2341/22s-pa03-MuhAsh99/cmake-build-debug && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /Users/muhammad/Desktop/CS2341/22s-pa03-MuhAsh99 /Users/muhammad/Desktop/CS2341/22s-pa03-MuhAsh99 /Users/muhammad/Desktop/CS2341/22s-pa03-MuhAsh99/cmake-build-debug /Users/muhammad/Desktop/CS2341/22s-pa03-MuhAsh99/cmake-build-debug /Users/muhammad/Desktop/CS2341/22s-pa03-MuhAsh99/cmake-build-debug/CMakeFiles/PA03_sorting_mystery.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/PA03_sorting_mystery.dir/depend

